# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const_test.xdc

# IP: ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet
