# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gm/Vivado Projects/complete_det_new_comblock_psclock/complete_det_new_comblock_psclock.srcs/sources_1/ip/cmpy_0/cmpy_0.xci
# IP: The module: 'cmpy_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gm/Vivado Projects/complete_det_new_comblock_psclock/complete_det_new_comblock_psclock.gen/sources_1/ip/cmpy_0/cmpy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmpy_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/gm/Vivado Projects/complete_det_new_comblock_psclock/complete_det_new_comblock_psclock.srcs/sources_1/ip/cmpy_0/cmpy_0.xci
# IP: The module: 'cmpy_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gm/Vivado Projects/complete_det_new_comblock_psclock/complete_det_new_comblock_psclock.gen/sources_1/ip/cmpy_0/cmpy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmpy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
