# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const_test.xdc

# Block Designs: bd/comblock_setup/comblock_setup.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comblock_setup || ORIG_REF_NAME==comblock_setup} -quiet] -quiet

# IP: bd/comblock_setup/ip/comblock_setup_comblock_0_0/comblock_setup_comblock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comblock_setup_comblock_0_0 || ORIG_REF_NAME==comblock_setup_comblock_0_0} -quiet] -quiet

# IP: bd/comblock_setup/ip/comblock_setup_processing_system7_0_1/comblock_setup_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comblock_setup_processing_system7_0_1 || ORIG_REF_NAME==comblock_setup_processing_system7_0_1} -quiet] -quiet

# IP: bd/comblock_setup/ip/comblock_setup_auto_pc_0/comblock_setup_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comblock_setup_auto_pc_0 || ORIG_REF_NAME==comblock_setup_auto_pc_0} -quiet] -quiet

# IP: bd/comblock_setup/ip/comblock_setup_ps7_0_axi_periph_1/comblock_setup_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comblock_setup_ps7_0_axi_periph_1 || ORIG_REF_NAME==comblock_setup_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/comblock_setup/ip/comblock_setup_rst_ps7_0_100M_1/comblock_setup_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==comblock_setup_rst_ps7_0_100M_1 || ORIG_REF_NAME==comblock_setup_rst_ps7_0_100M_1} -quiet] -quiet

# IP: ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# XDC: c:/Users/gm/Vivado Projects/complete_det_final_full_and_red/complete_det_final_full_and_red.gen/sources_1/bd/comblock_setup/comblock_setup_ooc.xdc
