# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gm/Vivado Projects/complete_det_final/complete_det_final.srcs/sources_1/ip/cmpy_1/cmpy_1.xci
# IP: The module: 'cmpy_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gm/Vivado Projects/complete_det_final/complete_det_final.gen/sources_1/ip/cmpy_1/cmpy_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmpy_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/gm/Vivado Projects/complete_det_final/complete_det_final.srcs/sources_1/ip/cmpy_1/cmpy_1.xci
# IP: The module: 'cmpy_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gm/Vivado Projects/complete_det_final/complete_det_final.gen/sources_1/ip/cmpy_1/cmpy_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmpy_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
