@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Sep 15 15:25:39 -0300 2026
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim fam_detector_top_tb_behav -key {Behavioral:sim_1:Functional:fam_detector_top_tb} -tclbatch fam_detector_top_tb.tcl -protoinst "protoinst_files/ps_comblock_setup.protoinst" -view C:/Users/gm/Vivado Projects/complete_det_modded_turbo/complete_det_modded_turbo.srcs/sim_1/imports/complete_det_modded/fam_detector_top_tb_behav.wcfg -log simulate.log"
call xsim  fam_detector_top_tb_behav -key {Behavioral:sim_1:Functional:fam_detector_top_tb} -tclbatch fam_detector_top_tb.tcl -protoinst "protoinst_files/ps_comblock_setup.protoinst" -view C:/Users/gm/Vivado Projects/complete_det_modded_turbo/complete_det_modded_turbo.srcs/sim_1/imports/complete_det_modded/fam_detector_top_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
